# Generated by Django 4.2.15 on 2024-10-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_userprofile_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
